name: Build on branch

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        branch: [v1.13.0]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\msys2_github\
        update: true
        install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-meson
            git
            base-devel
            autotools
        msystem: MINGW64
        path-type: strict
    - name: build
      shell: msys2 {0}
      run: |
        export HOME=${{ github.workspace }}
        export LDFLAGS="-static -static-libgcc -static-libstdc++ -s"
        git clone --depth 1 -b ${{ matrix.branch }} https://chromium.googlesource.com/webm/libvpx
        cd libvpx
        mkdir gcc_cmake
        cd gcc_cmake
        ../configure --enable-vp9_highbitdepth --enable-static
        make -j 2
    - name: postprocessing
      shell: cmd
      run: |
        copy /y libvpx\gcc_cmake\vpxenc.exe vpxenc.exe
        copy /y libvpx\gcc_cmake\vpxdec.exe vpxdec.exe
        copy /y libvpx\LICENSE LICENSE
        copy /y libvpx\PATENTS PATENTS
        7z a "libvpx_${{ matrix.branch }}.7z" vpxenc.exe vpxdec.exe LICENSE PATENTS
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: libvpx
        path: |
          libvpx_*.7z

  create_release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: libvpx
        path: artifacts
    
    - name: Get Date
      id: get_date
      run: |
        DATE_TIME=`date +'%Y-%m-%d-%H-%M-%S'`
        echo "DATE_TIME=${DATE_TIME}" >> $GITHUB_OUTPUT        
    # https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_NAME=Build-${{ steps.get_date.outputs.DATE_TIME }}
        TAG_NAME=build-${{ steps.get_date.outputs.DATE_TIME }}
        assets=()
        for asset in ${{ github.workspace }}/artifacts/*.7z; do
          assets+=("-a" "$asset")
        done
        gh release create "${assets[@]}" -m "$RELEASE_NAME" "$TAG_NAME"
